Ignore empty responses from Vosk that crash
When rec.FinalResult() returns an empty string, typically immediately after a
resume, it can cause the JSON decoder to fail. This patch simply ignores that
case and continues by returning an empty string to the caller.

Here is an example backtrace:

	Traceback (most recent call last):
	[...]
	  File "./nerd-dictation", line 1183, in text_from_vosk_pipe
		json_text = rec_handle_fn_wrapper_from_final_result()
	  File "./nerd-dictation", line 1046, in rec_handle_fn_wrapper_from_final_result
		json_data = json.loads(json_text)
	  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
		return _default_decoder.decode(s)
	  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
		obj, end = self.raw_decode(s, idx=_w(s, 0).end())
	  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
		raise JSONDecodeError("Expecting value", s, err.value) from None
	json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Signed-off-by: Eric Wheeler <vosk-git@z.ewheeler.org>